namespace MagicDraftStats.Models;

public static class FoundationsCardCatalog
{
    public static readonly HashSet<string> CardNames = new(StringComparer.Ordinal)
    {
        "Luminous Rebuke",
        "Prideful Parent",
        "Skyknight Squire",
        "Sun-Blessed Healer",
        "Valkyrie's Call",
        "Vanguard Seraph",
        "Arcane Epiphany",
        "Archmage of Runes",
        "Bigfin Bouncer",
        "Curator of Destinies",
        "Drake Hatcher",
        "Faebloom Trick",
        "Grappling Kraken",
        "High Fae Trickster",
        "Homunculus Horde",
        "Kaito, Cunning Infiltrator",
        "Kiora, the Rising Tide",
        "Mischievous Mystic",
        "Refute",
        "Rune-Sealed Wall",
        "Skyship Buccaneer",
        "Sphinx of Forgotten Lore",
        "Strix Lookout",
        "Uncharted Voyage",
        "Abyssal Harvester",
        "Arbiter of Woe",
        "Billowing Shriekmass",
        "Blasphemous Edict",
        "Bloodthirsty Conqueror",
        "Gutless Plunderer",
        "High-Society Hunter",
        "Hungry Ghoul",
        "Infestation Sage",
        "Nine-Lives Familiar",
        "Revenge of the Rats",
        "Sanguine Syphoner",
        "Seeker's Folly",
        "Stab",
        "Tinybones, Bauble Burglar",
        "Tragic Banshee",
        "Vampire Gourmand",
        "Vengeful Bloodwitch",
        "Zul Ashur, Lich Lord",
        "Bulk Up",
        "Chandra, Flameshaper",
        "Courageous Goblin",
        "Crackling Cyclops",
        "Dragon Trainer",
        "Electroduplicate",
        "Fiery Annihilation",
        "Gorehorn Raider",
        "Kellan, Planar Trailblazer",
        "Rite of the Dragoncaller",
        "Searslicer Goblin",
        "Slumbering Cerberus",
        "Sower of Chaos",
        "Strongbox Raider",
        "Twinflame Tyrant",
        "Beast-Kin Ranger",
        "Elvish Regrower",
        "Felling Blow",
        "Loot, Exuberant Explorer",
        "Mossborn Hydra",
        "Needletooth Pack",
        "Quilled Greatwurm",
        "Spinner of Souls",
        "Sylvan Scavenging",
        "Treetop Snarespinner",
        "Alesha, Who Laughs at Fate",
        "Anthem of Champions",
        "Ashroot Animist",
        "Dreadwing Scavenger",
        "Elenda, Saint of Dusk",
        "Fiendish Panda",
        "Koma, World-Eater",
        "Kykar, Zephyr Awakener",
        "Perforating Artist",
        "Wardens of the Cycle",
        "Zimone, Paradox Sculptor",
        "Leyline Axe",
        "Ravenous Amulet",
        "Scrawling Crawler",
        "Ajani, Caller of the Pride",
        "Ajani's Pridemate",
        "Angel of Finality",
        "Banishing Light",
        "Cathar Commando",
        "Day of Judgment",
        "Giada, Font of Hope",
        "Healer's Hawk",
        "Make Your Move",
        "Resolute Reinforcements",
        "Serra Angel",
        "Stroke of Midnight",
        "Youthful Valkyrie",
        "Aegis Turtle",
        "Aetherize",
        "Brineborn Cutthroat",
        "Essence Scatter",
        "Extravagant Replication",
        "Fleeting Distraction",
        "Micromancer",
        "Run Away Together",
        "Spectral Sailor",
        "Think Twice",
        "Tolarian Terror",
        "Witness Protection",
        "Bake into a Pie",
        "Burglar Rat",
        "Diregraf Ghoul",
        "Eaten Alive",
        "Hero's Downfall",
        "Liliana, Dreadhorde General",
        "Macabre Waltz",
        "Marauding Blight-Priest",
        "Phyrexian Arena",
        "Pilfer",
        "Reassembling Skeleton",
        "Rise of the Dark Realms",
        "Rune-Scarred Demon",
        "Vampire Nighthawk",
        "Zombify",
        "Abrade",
        "Axgard Cavalry",
        "Brazen Scourge",
        "Burst Lightning",
        "Drakuseth, Maw of Flames",
        "Etali, Primal Storm",
        "Fanatical Firebrand",
        "Firebrand Archer",
        "Firespitter Whelp",
        "Flamewake Phoenix",
        "Goblin Surprise",
        "Heartfire Immolator",
        "Involuntary Employment",
        "Slagstorm",
        "Thrill of Possibility",
        "Bite Down",
        "Broken Wings",
        "Bushwhack",
        "Dwynen, Gilt-Leaf Daen",
        "Dwynen's Elite",
        "Garruk's Uprising",
        "Genesis Wave",
        "Ghalta, Primal Hunger",
        "Giant Growth",
        "Gnarlid Colony",
        "Grow from the Ashes",
        "Inspiring Call",
        "Llanowar Elves",
        "Mild-Mannered Librarian",
        "Nessian Hornbeetle",
        "Overrun",
        "Scavenging Ooze",
        "Snakeskin Veil",
        "Vivien Reid",
        "Balmor, Battlemage Captain",
        "Consuming Aberration",
        "Empyrean Eagle",
        "Good-Fortune Unicorn",
        "Heroic Reinforcements",
        "Lathril, Blade of the Elves",
        "Muldrotha, the Gravetide",
        "Ruby, Daring Tracker",
        "Swiftblade Vindicator",
        "Tatyova, Benthic Druid",
        "Thousand-Year Storm",
        "Burnished Hart",
        "Goldvein Pick",
        "Heraldic Banner",
        "Meteor Golem",
        "Solemn Simulacrum",
        "Swiftfoot Boots",
        "Bloodfell Caves",
        "Blossoming Sands",
        "Dismal Backwater",
        "Evolving Wilds",
        "Jungle Hollow",
        "Rugged Highlands",
        "Scoured Barrens",
        "Swiftwater Cliffs",
        "Thornwood Falls",
        "Tranquil Cove",
        "Wind-Scarred Crag",
        "Plains",
        "Island",
        "Swamp",
        "Mountain",
        "Forest"
    };

    public static bool Contains(string cardName)
    {
        return !string.IsNullOrWhiteSpace(cardName) && CardNames.Contains(cardName);
    }
}
