namespace MagicDraftStats.Models;

public static class FoundationsCardCatalog
{
    public static readonly HashSet<string> CardNames = new(StringComparer.Ordinal)
    {
        "Sire of Seven Deaths",
        "Arahbo, the First Fang",
        "Cat Collector",
        "Celestial Armor",
        "Claws Out",
        "Dauntless Veteran",
        "Dazzling Angel",
        "Divine Resilience",
        "Exemplar of Light",
        "Felidar Savior",
        "Helpful Hunter",
        "Herald of Eternal Dawn",
        "Joust Through",
        "Luminous Rebuke",
        "Prideful Parent",
        "Skyknight Squire",
        "Sun-Blessed Healer",
        "Valkyrie's Call",
        "Vanguard Seraph",
        "Arcane Epiphany",
        "Archmage of Runes",
        "Bigfin Bouncer",
        "Curator of Destinies",
        "Drake Hatcher",
        "Faebloom Trick",
        "Grappling Kraken",
        "High Fae Trickster",
        "Homunculus Horde",
        "Kaito, Cunning Infiltrator",
        "Kiora, the Rising Tide",
        "Mischievous Mystic",
        "Refute",
        "Rune-Sealed Wall",
        "Skyship Buccaneer",
        "Sphinx of Forgotten Lore",
        "Strix Lookout",
        "Uncharted Voyage",
        "Abyssal Harvester",
        "Arbiter of Woe",
        "Billowing Shriekmass",
        "Blasphemous Edict",
        "Bloodthirsty Conqueror",
        "Gutless Plunderer",
        "High-Society Hunter",
        "Hungry Ghoul",
        "Infestation Sage",
        "Nine-Lives Familiar",
        "Revenge of the Rats",
        "Sanguine Syphoner",
        "Seeker's Folly",
        "Stab",
        "Tinybones, Bauble Burglar",
        "Tragic Banshee",
        "Vampire Gourmand",
        "Vengeful Bloodwitch",
        "Zul Ashur, Lich Lord",
        "Bulk Up",
        "Chandra, Flameshaper",
        "Courageous Goblin",
        "Crackling Cyclops",
        "Dragon Trainer",
        "Electroduplicate",
        "Fiery Annihilation",
        "Gorehorn Raider",
        "Kellan, Planar Trailblazer",
        "Rite of the Dragoncaller",
        "Searslicer Goblin",
        "Slumbering Cerberus",
        "Sower of Chaos",
        "Strongbox Raider",
        "Twinflame Tyrant",
        "Beast-Kin Ranger",
        "Elvish Regrower",
        "Felling Blow",
        "Loot, Exuberant Explorer",
        "Mossborn Hydra",
        "Needletooth Pack",
        "Quilled Greatwurm",
        "Spinner of Souls",
        "Sylvan Scavenging",
        "Treetop Snarespinner",
        "Alesha, Who Laughs at Fate",
        "Anthem of Champions",
        "Ashroot Animist",
        "Dreadwing Scavenger",
        "Elenda, Saint of Dusk",
        "Fiendish Panda",
        "Koma, World-Eater",
        "Kykar, Zephyr Awakener",
        "Perforating Artist",
        "Wardens of the Cycle",
        "Zimone, Paradox Sculptor",
        "Leyline Axe",
        "Ravenous Amulet",
        "Scrawling Crawler",
        "Ajani, Caller of the Pride",
        "Ajani's Pridemate",
        "Angel of Finality",
        "Banishing Light",
        "Cathar Commando",
        "Day of Judgment",
        "Giada, Font of Hope",
        "Healer's Hawk",
        "Make Your Move",
        "Resolute Reinforcements",
        "Serra Angel",
        "Stroke of Midnight",
        "Youthful Valkyrie",
        "Aegis Turtle",
        "Aetherize",
        "Brineborn Cutthroat",
        "Essence Scatter",
        "Extravagant Replication",
        "Fleeting Distraction",
        "Micromancer",
        "Run Away Together",
        "Spectral Sailor",
        "Think Twice",
        "Tolarian Terror",
        "Witness Protection",
        "Bake into a Pie",
        "Burglar Rat",
        "Diregraf Ghoul",
        "Eaten Alive",
        "Hero's Downfall",
        "Liliana, Dreadhorde General",
        "Macabre Waltz",
        "Marauding Blight-Priest",
        "Phyrexian Arena",
        "Pilfer",
        "Reassembling Skeleton",
        "Rise of the Dark Realms",
        "Rune-Scarred Demon",
        "Vampire Nighthawk",
        "Zombify",
        "Abrade",
        "Axgard Cavalry",
        "Brazen Scourge",
        "Burst Lightning",
        "Drakuseth, Maw of Flames",
        "Etali, Primal Storm",
        "Fanatical Firebrand",
        "Firebrand Archer",
        "Firespitter Whelp",
        "Flamewake Phoenix",
        "Goblin Surprise",
        "Heartfire Immolator",
        "Involuntary Employment",
        "Slagstorm",
        "Thrill of Possibility",
        "Bite Down",
        "Broken Wings",
        "Bushwhack",
        "Dwynen, Gilt-Leaf Daen",
        "Dwynen's Elite",
        "Garruk's Uprising",
        "Genesis Wave",
        "Ghalta, Primal Hunger",
        "Giant Growth",
        "Gnarlid Colony",
        "Grow from the Ashes",
        "Inspiring Call",
        "Llanowar Elves",
        "Mild-Mannered Librarian",
        "Nessian Hornbeetle",
        "Overrun",
        "Scavenging Ooze",
        "Snakeskin Veil",
        "Vivien Reid",
        "Balmor, Battlemage Captain",
        "Consuming Aberration",
        "Empyrean Eagle",
        "Good-Fortune Unicorn",
        "Heroic Reinforcements",
        "Lathril, Blade of the Elves",
        "Muldrotha, the Gravetide",
        "Ruby, Daring Tracker",
        "Swiftblade Vindicator",
        "Tatyova, Benthic Druid",
        "Thousand-Year Storm",
        "Burnished Hart",
        "Goldvein Pick",
        "Heraldic Banner",
        "Meteor Golem",
        "Solemn Simulacrum",
        "Swiftfoot Boots",
        "Bloodfell Caves",
        "Blossoming Sands",
        "Dismal Backwater",
        "Evolving Wilds",
        "Jungle Hollow",
        "Rugged Highlands",
        "Scoured Barrens",
        "Swiftwater Cliffs",
        "Thornwood Falls",
        "Tranquil Cove",
        "Wind-Scarred Crag",
        "Ancestor Dragon",
        "Deadly Riposte",
        "Inspiring Overseer",
        "Jazal Goldmane",
        "Leonin Vanguard",
        "Pacifism",
        "Prayer of Binding",
        "Twinblade Paladin",
        "Cancel",
        "Corsair Captain",
        "Exclusion Mage",
        "Into the Roil",
        "Kitesail Corsair",
        "Mystic Archaeologist",
        "Opt",
        "Quick Study",
        "Storm Fleet Spy",
        "Bloodtithe Collector",
        "Crossway Troublemakers",
        "Deadly Plot",
        "Moment of Craving",
        "Offer Immortality",
        "Vampire Interloper",
        "Carnelian Orb of Dragonkind",
        "Dragon Fodder",
        "Dragonlord's Servant",
        "Dropkick Bomber",
        "Goblin Oriflamme",
        "Rapacious Dragon",
        "Scorching Dragonfire",
        "Seize the Spoils",
        "Terror of Mount Velus",
        "Volley Veteran",
        "Aggressive Mammoth",
        "Druid of the Cowl",
        "Joraga Invocation",
        "Thornweald Archer",
        "Thrashing Brontodon",
        "Angelic Destiny",
        "Charming Prince",
        "Dawnwing Marshal",
        "Felidar Retreat",
        "Fumigate",
        "Mentor of the Meek",
        "Regal Caracal",
        "Stasis Snare",
        "Valorous Stance",
        "Arcanis the Omnipotent",
        "Chart a Course",
        "Finale of Revelation",
        "Fog Bank",
        "Gateway Sneak",
        "Harbinger of the Tides",
        "Mystical Teachings",
        "River's Rebuke",
        "Shipwreck Dowser",
        "Unsummon",
        "Voracious Greatshark",
        "Desecration Demon",
        "Driver of the Dead",
        "Midnight Reaper",
        "Nullpriest of Oblivion",
        "Sanguine Indulgence",
        "Tribute to Hunger",
        "Vampiric Rites",
        "Vile Entomber",
        "Crash Through",
        "Dragonmaster Outcast",
        "Ghitu Lavarunner",
        "Lathliss, Dragon Queen",
        "Obliterating Bolt",
        "Redcap Gutter-Dweller",
        "Stromkirk Noble",
        "Taurean Mauler",
        "Viashino Pyromancer",
        "Circuitous Route",
        "Fierce Empath",
        "Fynn, the Fangbearer",
        "Gnarlback Rhino",
        "Heroes' Bane",
        "Ordeal of Nylea",
        "Predator Ooze",
        "Primal Might",
        "Primeval Bounty",
        "Rampaging Baloths",
        "Springbloom Druid",
        "Surrak, the Hunt Caller",
        "Venom Connoisseur",
        "Vizier of the Menagerie",
        "Wildborn Preserver",
        "Aurelia, the Warleader",
        "Ayli, Eternal Pilgrim",
        "Cloudblazer",
        "Deadly Brew",
        "Drogskol Reaver",
        "Dryad Militant",
        "Enigma Drake",
        "Garna, Bloodfist of Keld",
        "Halana and Alena, Partners",
        "Immersturm Predator",
        "Maelstrom Pulse",
        "Mortify",
        "Ovika, Enigma Goliath",
        "Prime Speaker Zegana",
        "Savage Ventmaw",
        "Wilt-Leaf Liege",
        "Basilisk Collar",
        "Cultivator's Caravan",
        "Gate Colossus",
        "Mazemind Tome",
        "Ramos, Dragon Engine",
        "Steel Hellkite",
        "Three Tree Mascot",
        "Azorius Guildgate",
        "Boros Guildgate",
        "Crawling Barrens",
        "Cryptic Caves",
        "Dimir Guildgate",
        "Golgari Guildgate",
        "Gruul Guildgate",
        "Izzet Guildgate",
        "Orzhov Guildgate",
        "Rakdos Guildgate",
        "Selesnya Guildgate",
        "Simic Guildgate",
        "Temple of Abandon",
        "Temple of Deceit",
        "Temple of Enlightenment",
        "Temple of Epiphany",
        "Temple of Malady",
        "Temple of Malice",
        "Temple of Mystery",
        "Temple of Plenty",
        "Temple of Silence",
        "Temple of Triumph",
        "Lyra Dawnbringer",
        "Make a Stand",
        "Confiscate",
        "Rite of Replication",
        "Feed the Swarm",
        "Gatekeeper of Malakir",
        "Massacre Wurm",
        "Guttersnipe",
        "Impact Tremors",
        "Imperious Perfect",
        "Pelakka Wurm",
        "Boros Charm",
        "Adaptive Automaton",
        "Gilded Lotus",
        "Hedron Archive",
        "Hinterland Sanctifier",
        "Plains",
        "Island",
        "Swamp",
        "Mountain",
        "Forest"
    };

    public static bool Contains(string cardName)
    {
        return !string.IsNullOrWhiteSpace(cardName) && CardNames.Contains(cardName);
    }
}
